package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Produto;

public class TelaPrincipal extends javax.swing.JFrame {

    ArrayList<Produto> listaProd = new ArrayList<>();

    public TelaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(this);
        Produto p = new Produto(123456, "Produto Teste", "Marca Teste", 44.86, 345);
        listaProd.add(p);
        this.atualizarTabela();

    }

    private void atualizarTabela() {
        // Pega o modelo da tabelaAlunos, como modelo padrão
        DefaultTableModel modelo = (DefaultTableModel) tabelaProdutos.getModel();
        modelo.setRowCount(0);
        for (Produto p : listaProd) {
            modelo.addRow(new Object[]{p.getCodigo(), p.getDescricao(), p.getValor()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botNovoProd5 = new javax.swing.JButton();
        painelManterProdTop = new javax.swing.JPanel();
        labelManterProd = new javax.swing.JLabel();
        painelManterProdBotton = new javax.swing.JPanel();
        botNovoProd = new javax.swing.JButton();
        botExcluirProd = new javax.swing.JButton();
        botAltProd = new javax.swing.JButton();
        botVisuProd = new javax.swing.JButton();
        botComprarProd = new javax.swing.JButton();
        botVenderProd = new javax.swing.JButton();
        botSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();

        botNovoProd5.setBackground(new java.awt.Color(153, 255, 255));
        botNovoProd5.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        botNovoProd5.setText("Comprar");
        botNovoProd5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botNovoProd5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(null);

        painelManterProdTop.setBackground(new java.awt.Color(204, 204, 204));
        painelManterProdTop.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelManterProd.setBackground(new java.awt.Color(204, 204, 204));
        labelManterProd.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        labelManterProd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelManterProd.setText("Manutenção de Produtos");

        javax.swing.GroupLayout painelManterProdTopLayout = new javax.swing.GroupLayout(painelManterProdTop);
        painelManterProdTop.setLayout(painelManterProdTopLayout);
        painelManterProdTopLayout.setHorizontalGroup(
            painelManterProdTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelManterProdTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelManterProd)
                .addGap(224, 224, 224))
        );
        painelManterProdTopLayout.setVerticalGroup(
            painelManterProdTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelManterProdTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelManterProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelManterProdBotton.setBackground(new java.awt.Color(204, 204, 204));
        painelManterProdBotton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painelManterProdBotton.setMaximumSize(new java.awt.Dimension(600, 50));
        painelManterProdBotton.setPreferredSize(new java.awt.Dimension(600, 32));

        botNovoProd.setBackground(new java.awt.Color(153, 255, 255));
        botNovoProd.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        botNovoProd.setText("Novo");
        botNovoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botNovoProdActionPerformed(evt);
            }
        });

        botExcluirProd.setBackground(new java.awt.Color(153, 255, 255));
        botExcluirProd.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        botExcluirProd.setText("Excluir");
        botExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botExcluirProdActionPerformed(evt);
            }
        });

        botAltProd.setBackground(new java.awt.Color(153, 255, 255));
        botAltProd.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        botAltProd.setText("Alterar");
        botAltProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAltProdActionPerformed(evt);
            }
        });

        botVisuProd.setBackground(new java.awt.Color(153, 255, 255));
        botVisuProd.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        botVisuProd.setText("Visualizar");
        botVisuProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVisuProdActionPerformed(evt);
            }
        });

        botComprarProd.setBackground(new java.awt.Color(153, 255, 255));
        botComprarProd.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        botComprarProd.setText("Comprar");
        botComprarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botComprarProdActionPerformed(evt);
            }
        });

        botVenderProd.setBackground(new java.awt.Color(153, 255, 255));
        botVenderProd.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        botVenderProd.setText("Vender");
        botVenderProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVenderProdActionPerformed(evt);
            }
        });

        botSair.setBackground(new java.awt.Color(153, 255, 255));
        botSair.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        botSair.setText("Sair");
        botSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelManterProdBottonLayout = new javax.swing.GroupLayout(painelManterProdBotton);
        painelManterProdBotton.setLayout(painelManterProdBottonLayout);
        painelManterProdBottonLayout.setHorizontalGroup(
            painelManterProdBottonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelManterProdBottonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botNovoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botExcluirProd, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botAltProd, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botVisuProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botComprarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botVenderProd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(botSair, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelManterProdBottonLayout.setVerticalGroup(
            painelManterProdBottonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelManterProdBottonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelManterProdBottonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelManterProdBottonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botVisuProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botComprarProd))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelManterProdBottonLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(painelManterProdBottonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botNovoProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botExcluirProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botAltProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botVenderProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Valor"
            }
        ));
        jScrollPane1.setViewportView(tabelaProdutos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelManterProdTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelManterProdBotton, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelManterProdTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelManterProdBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botNovoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botNovoProdActionPerformed
        DialogDadosProduto tela = new DialogDadosProduto(this, true);

        tela.setVisible(true);
        listaProd.add(tela.getProduto());

        this.atualizarTabela();

        tela.dispose();

    }//GEN-LAST:event_botNovoProdActionPerformed

    private void botExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botExcluirProdActionPerformed
        int linha = this.tabelaProdutos.getSelectedRow();

        if (linha != 1) {
            JOptionPane.showConfirmDialog(null, "Confimar");
                listaProd.remove(linha);
            this.atualizarTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha!");
        }

    }//GEN-LAST:event_botExcluirProdActionPerformed

    private void botAltProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAltProdActionPerformed
        // Pega a linha selecionada (-1 senão estiver selecionada)
        int linha = this.tabelaProdutos.getSelectedRow();

        if (linha != -1) {
            DialogDadosProduto tela = new DialogDadosProduto(this, true);
            tela.setProduto(this.listaProd.get(linha));
            tela.bloquearEstoque();
            tela.setVisible(true);

            // Troca os dados novos, inserirndo no lugar dos antigos
            listaProd.set(linha, tela.getProduto());
            this.atualizarTabela();
            tela.setVisible(false);
            tela.dispose();
        } else {
            // Não selecionou uma linha da tabela, apresentar mensagem
            JOptionPane.showMessageDialog(null, "Selecione uma linha.");
        }
    }//GEN-LAST:event_botAltProdActionPerformed

    private void botVisuProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVisuProdActionPerformed
        int linha = this.tabelaProdutos.getSelectedRow();

        if (linha != -1) {
            DialogDadosProduto tela = new DialogDadosProduto(this, true);
            tela.setProduto(this.listaProd.get(linha));
            tela.bloquearAll();
            tela.setVisible(true);

            tela.dispose();
        } else {
            // Não selecionou uma linha da tabela, apresentar mensagem
            JOptionPane.showMessageDialog(null, "Selecione uma linha.");
        }
    }//GEN-LAST:event_botVisuProdActionPerformed

    private void botComprarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botComprarProdActionPerformed
        int linha = this.tabelaProdutos.getSelectedRow();

        if (linha != -1) {
            DialogCompraVendaProduto tela = new DialogCompraVendaProduto(this, true);
            tela.comprar();
            tela.bloquear();
            tela.setProduto(this.listaProd.get(linha));
            tela.setVisible(true);

            this.listaProd.get(linha).comprar(tela.qtdC());
            this.atualizarTabela();
            tela.dispose();
        } else {
            // Não selecionou uma linha da tabela, apresentar mensagem
            JOptionPane.showMessageDialog(null, "Selecione uma linha.");
        }
    }//GEN-LAST:event_botComprarProdActionPerformed

    private void botNovoProd5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botNovoProd5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botNovoProd5ActionPerformed

    private void botVenderProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVenderProdActionPerformed
        int linha = this.tabelaProdutos.getSelectedRow();

        if (linha != -1) {
            DialogCompraVendaProduto tela = new DialogCompraVendaProduto(this, true);
            tela.vender();
            tela.bloquear();
            tela.setProduto(listaProd.get(linha));
            tela.setVisible(true);

            this.listaProd.get(linha).vender(tela.qtdC());
            this.atualizarTabela();

            tela.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma lina!");
        }
    }//GEN-LAST:event_botVenderProdActionPerformed

    private void botSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_botSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAltProd;
    private javax.swing.JButton botComprarProd;
    private javax.swing.JButton botExcluirProd;
    private javax.swing.JButton botNovoProd;
    private javax.swing.JButton botNovoProd5;
    private javax.swing.JButton botSair;
    private javax.swing.JButton botVenderProd;
    private javax.swing.JButton botVisuProd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelManterProd;
    private javax.swing.JPanel painelManterProdBotton;
    private javax.swing.JPanel painelManterProdTop;
    private javax.swing.JTable tabelaProdutos;
    // End of variables declaration//GEN-END:variables
}
